config/routes.rb
Rails.application.routes.draw do
  get 'comments/create'
  root controller: :articles, action: :index
  resources :articles, only: [:new, :create, :show] do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    has_many :comments
    validates_presence_of :title, :content, :author
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article

  validates_presence_of :content
  validates_confirmation_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def show
    @article = Article.find(params[:id])
  end
  
  def create
    @article = Article.create(article_params)
    if @article.persisted?
      redirect_to root_path, notice: 'Article was successfully created.'
    else
      flash[:error] = 'Your article could not be saved'
      render :new
    end

  end

  private

  def article_params
    params.require(:article).permit(:title, :content)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    article = Article.find(params[:article_id])
    Comment.create(email: params[:email], content: params[:comment], article: article)
    flash[:succes] = 'Your comment was added'
    redirect_to article_path(article)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/create.html.erb
<p>Create page</p>

app/views/articles/index.html.erb
<%= link_to "New Article", new_article_path %>

<h1>Articles</h1>

<% @articles.each do |article| %>
    <%= link_to article.title, article_path(article) %>
    <p><%= article.content %></p>
    <p><%= "Written by #{article.author} at #{article.created_at}" %></p>
<% end %>

app/views/articles/new.html.erb
<%= form_with model: @article, local: true do |form| %>
      <%= form.label :title %>
      <%= form.text_field :title %>
      <br \>
      <%= form.label :content %>
      <%= form.text_area :content %>
      <br \>
      <%= form.submit url: 'article_path' %>
<% end %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.content %>
</p>

<%= form_with url: article_comments_path(@article), local: true do |form| %>
      <%= form.label :email %>
      <%= form.text_field :email %>
      <br \>
      <%= form.label :comment %>
      <%= form.text_area :comment %>
      <br \>
      <%= form.submit %>
<% end %>

<% if @article.comments.any? %>
  <% @article.comments.each do |comment| %>
    <p>
      <%= "Commented by: #{comment.email}" %>
    </p>
    <p>
      <%= comment.content %>
    </p>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsDemo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= notice %>
    <%= flash[:error] %>
    <%= flash[:succes] %>
    <%= yield %>
  </body>
</html>